name: TEST

on:
  push:
    branches:
      - main

jobs:
  trigger-docs-update:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
          owner: nuvibit-terraform-collection
          repo: docs
          workflow_id: dynamic-docs
          ref: main
        env:
          GITHUB_TOKEN: ${{ secrets.GHE_API_TOKEN }}
